### ISSUE TITLE
Researcher "AmmonRa" discloses unresolved bus fare card vulnerability, police informed

### ISSUE THREAD

**Issue by TCFox** [disclose/research-threats#15]
At [Kiwicon 7](https://2013.kiwicon.org/the-con/talks.1#e112) (2013-11-09), researcher "AmmonRa" [disclosed a series of vulnerabilities regarding Christchurch's "Metro Card" bus fare system](https://www.rnz.co.nz/news/the-wireless/370448/smart-cards-not-so-smart). He previously reported the security flaw to Environment Canterbury, the group that oversees the bus network, three months prior, but nothing had been done.

After disclosing the vulnerability publicly, [Environment Canterbury director operations Wayne Holton-Jeffreys had called the police](https://www.stuff.co.nz/the-press/news/transport/9386649/ECan-public-transport-card-hacked) (but was unsure if any charges would be laid).

**Comment by sickcodes** [comment]
Thanks for that! Did you want to submit as a PR :)?

**Comment by sickcodes** [comment]
| 2013-11-10 | [Christchurch Public Transport Card (ECan)](https://www.ecan.govt.nz/) | [William "AmmonRa" Turner](https://twitter.com/amm0nra) | Insecure Public Transport Card System | At [Kiwicon 7](https://2013.kiwicon.org/the-con/talks.1#e112) (2013-11-09), researcher "AmmonRa" [disclosed a series of vulnerabilities regarding Christchurch's "Metro Card" bus fare system](https://www.rnz.co.nz/news/the-wireless/370448/smart-cards-not-so-smart). He previously reported the security flaw to Environment Canterbury, the group that oversees the bus network, three months prior, but nothing had been done. Without merit, after disclosing the vulnerability publicly, [Environment Canterbury director operations Wayne Holton-Jeffreys had called the police](https://www.stuff.co.nz/the-press/news/transport/9386649/ECan-public-transport-card-hacked) (but was unsure if any charges would be laid). In essense, the Director of operations, Wayne Holton-Jeffreys, failed to protect their own systems and passed the buck to a hacker for exposing a loophole where 70,000 free rides were allegedly ridden following the talk at Kiwicon. ECan "called the police" over the flaws that they themselves created, and ignored. |
|------------|------------------------------------------------------------------------|---------------------------------------------------------|---------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
