### ISSUE TITLE
Broken link to C&D letter for 2015 Impero Software incident

### ISSUE THREAD

**Issue by JayAndCatchFire** [disclose/research-threats#19]
There's a broken link to the C&D letter for the 2015-07-13 Impero Software incident.  The original link (https://pdf.yt/d/fRcZ1TWHaDkwz-Ea) is not resolving for me.  There are a few choices to fix this:
- [Archive.org mirrors the original link](https://archive.org/details/pdfy-fRcZ1TWHaDkwz-Ea)
  - and offers a [direct download of the original](https://archive.org/download/pdfy-fRcZ1TWHaDkwz-Ea/Letter%20to%20Mr%20Zammis%20A%20Clark%20dated%2013%20July%202015.pdf)
  - as well as an [OCR'd searchable text version](https://archive.org/download/pdfy-fRcZ1TWHaDkwz-Ea/Letter%20to%20Mr%20Zammis%20A%20Clark%20dated%2013%20July%202015_text.pdf) that's also better for screen readers
- Cybergibbons (🤷) has a [copy of the original](https://cybergibbons.com/wp-content/uploads/2015/07/Letter-to-Mr-Zammis-A-Clark-dated-13-July-2015.pdf) on their wordpress site
- LizardHQ (🤷) has a [copy of it on their github repo for their site](https://github.com/lizardhq/lizardhq-website/blob/4b83f20d9687342335e277c994fbfe7187c86e8d/files/Letter%20to%20Mr%20Zammis%20A%20Clark%20dated%2013%20July%202015.pdf)
- A copy can be added to this repo in the goodies directory and the README can link to that

I'd be happy to make a PR, just let me know what's preferred.  And if it's adding it to this repo in the goodies directory, which version is preferred?  The original or the OCR, searchable, screen reader friendly version that archive.org automatically created?

**Comment by attritionorg** [comment]
I think adding a copy to goodies to archive and linking to that is fine, or one of the archive.org links.

**Comment by JayAndCatchFire** [comment]
Actually, I'm going to add the original version to my PR for archival reasons.  The OCR one has a few mistakes in the text translation (such as "Gateley Plc" being converted to "Gateley _Pic_".  Also, the OCR version renders a little poorer on my computer.  Someone can always OCR it again or replace it.

**Comment by JayAndCatchFire** [comment]
Actually, I just found that the pdf is already in the goodies folder and was added 14 days ago by @sickcodes.  I'll just update the link to point to it.

**Comment by JayAndCatchFire** [comment]
Fixed by #21
