### ISSUE TITLE
Radiodity Open GD77 firmware

### ISSUE THREAD

**Issue by attritionorg** [disclose/research-threats#20]
Posting here for reference, as this may qualify for inclusion pending more details.

https://twitter.com/BryanSmart/status/1384243611110285321

URGENT! If you, or someone you know, is using the Open GD77 firmware for Radiodity ham radios, the only talking handheld FM/DMR radio, the author is being forced to take it down due to some licensing issue. Not much details yet. He's leaving it up for 48 hours, then it's gone.

**Comment by sickcodes** [comment]
Interesting, wonder if the license was broken or not

**Comment by sickcodes** [comment]
Updates to this event: https://kk4vcz.com/posts/th-d74-firmware/

Repo: https://github.com/cr/thd74/

Nothing from Kenwood's it seems, so probably worth closing this issue if you want?

**Comment by sickcodes** [comment]
Firmware decryption tool was posted here: https://github.com/cr/thd74/

No legal threats were involved, so gonna close for now.
