### ISSUE TITLE
My Xerox talk finally happened

### ISSUE THREAD

**Issue by trou** [disclose/research-threats#26]
Hi,
I could finally present it yesterday at INFILTRATE
Slides: <https://syscall.eu/pdf/INFILTRATE2020-RIGO-Xerox-final.pdf>
Video: <https://vimeo.com/showcase/8085537/video/539693997>

Some reporting about it: <https://portswigger.net/daily-swig/xerox-vulnerability-disclosure-legal-threat-withdrawn>

**Comment by sickcodes** [comment]
Hey @trou  will add this one shortly!
