### ISSUE TITLE
MIT threatened to sue after I reported a security vulnerability

### ISSUE THREAD

**Issue by D4stiny** [disclose/research-threats#27]
Thought I'd open a new issue regarding my experiences with the Massachusetts Institute of Technology four years ago. I had found an exposed WordPress debug log that had been recording for about a year when I found it (4GB+ of data). All PII has been removed except my own, which is already publicly available.

The legal threat:
![image](https://user-images.githubusercontent.com/16182786/116013558-cfb5b380-a5fe-11eb-876d-038cf4f76cef.png)
![image](https://user-images.githubusercontent.com/16182786/116013563-d3e1d100-a5fe-11eb-9463-76569eeb35db.png)

My email to the head of MIT's IT department:
![image](https://user-images.githubusercontent.com/16182786/116013571-de9c6600-a5fe-11eb-9dc6-fc198e7251c9.png)

MIT's IT Head response:
![image](https://user-images.githubusercontent.com/16182786/116013575-e3f9b080-a5fe-11eb-9571-42b66f9d2035.png)

Follow-up from original staff member encouraging that I stay away from security:
![image](https://user-images.githubusercontent.com/16182786/116013585-f5db5380-a5fe-11eb-924c-640cac7204ff.png)
![image](https://user-images.githubusercontent.com/16182786/116013589-f8d64400-a5fe-11eb-8eaf-5fae6c716b9d.png)

**Comment by sickcodes** [comment]
Wow! That's an interesting chain of email. What department at MIT? 

Interestingly condescending individual that you spoke to 😂 have you told that individual you are now working at Zoom?

**Comment by D4stiny** [comment]
@sickcodes It was MIT's Information Systems & Technology (IT) department. I have not told them of my success, but I have considered it.

**Comment by sickcodes** [comment]
You should, would be a cool follow up. Do they have a GitHub? It would be nice to tag them so they have a chance to PR too @MIT

**Comment by D4stiny** [comment]
The specific staff member that sent the threat/final reply does have a GitHub account, but it's not linked to an MIT IT team I can tag. Even if they were in the wrong, I am not interested in doxing them.

**Comment by sickcodes** [comment]
Neither am I, and that's not what we're about either, but if you wanted to privately ping them, or I could if you're too busy, just thought they maybe would be interested in a response given it's been a hot minute.

**Comment by sickcodes** [comment]
Do you mind if I compile these into a PDF?

**Comment by sickcodes** [comment]
Fixed in https://github.com/disclose/research-threats/pull/30

https://github.com/disclose/research-threats/blob/MIT-D4stiny/goodies/MIT_threatened_to_sue_after_I_reported_a_security_vulnerability_%2327.pdf

**Comment by spwn3r49sd3r00** [comment]
Lol that school is a joke anyways, trust me you don’t wanna report bugs to any universities, especially them and the Stanford. Let them suffer.
