### ISSUE TITLE
2021: German researcher Lilith Wittmann

### ISSUE THREAD

**Issue by GKnirps** [disclose/research-threats#51]
|2021-08-04|[CDU](https://www.cdu.de/) (German political party)|[Lilith Wittmann](https://lilithwittmann.medium.com/) |In 2021, during the election campaign for the German Bundestag, s security researcher named Lilith Wittmann [discovered and published](https://lilithwittmann.medium.com/wenn-die-cdu-ihren-wahlkampf-digitalisiert-a3e9a0398b4d) data security issues in the election campaign app used by the German parties CDU, CSU and Volkspartei. The CDU [pressed charges](https://www.heise.de/news/Sicherheitsluecken-in-CDU-connect-App-Strafverfahren-gegen-Entdeckerin-6154663.html) against Wittmann but [withdrew](https://www.heise.de/news/CDU-zieht-Anzeige-wegen-CDU-connect-App-zurueck-und-bittet-um-Entschuldigung-6155229.html) later after a public outcry and apologized.|

**Comment by sickcodes** [comment]
Added! Thank you :)
