### ISSUE TITLE
Blue Coat talk

### ISSUE THREAD

**Issue by trou** [disclose/research-threats#8]
Hi,
regarding my Blue Coat talk, I could present it (almost unchanged) months later at Ruxcon and Black Hat Europe
see <https://syscall.eu/> for slides and video link

**Comment by sickcodes** [comment]
_However, as of 2021-04-14, the researcher confirmed that he was able to present the talk months later at Ruxcon and Black Hat Europe. See https://github.com/disclose/research-threats/issues/8 and the slides & video are available at https://syscall.eu/_

How does that sound? Also thank you for helping us keep it up to date!
